
import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'es' | 'pt';

type LanguageContextType = {
  language: Language;
  setLanguage: (lang: Language) => void;
  translate: (key: string) => string;
};

const translations = {
  es: {
    welcome: "Bienvenido a Accu-Tech Healthineers",
    welcomeSubtitle: "Tu compañero para el control de la glucosa sin dolor",
    welcomeToApp: "La nueva era del control de la diabetes",
    thankYouMessage: "¡Gracias por tu compra! Estamos preparando tu dispositivo",
    userTestimonial: "Por fin puedo medir mi glucosa sin pincharme los dedos. ¡Es increíble!",
    testimonialAuthor: "María G., usuario de Accu-Tech Healthineers",
    deviceArrivalMessage: "Mientras esperas la llegada de tu Accu-Tech Healthineers, exploremos la aplicación",
    selectLanguage: "Seleccionar idioma",
    spanish: "Español",
    portuguese: "Portugués",
    continue: "Continuar",
    skip: "Omitir",
    next: "Siguiente",
    back: "Atrás",
    getStarted: "Empezar",
    howItWorks: "¿Cómo funciona?",
    laserTechnologyIntro: "Nuestra tecnología láser revolucionaria mide tu glucosa sin dolor",
    laserEmissionTitle: "Emisión de láser",
    laserEmissionDesc: "Un láser infrarrojo seguro penetra ligeramente en la piel",
    bloodlessAnalysisTitle: "Análisis sin sangre",
    bloodlessAnalysisDesc: "La luz reflejada analiza las moléculas de glucosa",
    instantReadingTitle: "Lectura instantánea",
    instantReadingDesc: "El dispositivo calcula tu nivel de glucosa en segundos",
    scientificallyProven: "Tecnología respaldada por investigación científica avanzada",
    keyBenefits: "Beneficios principales",
    benefitsIntro: "Descubre por qué Accu-Tech Healthineers transformará tu vida",
    noPainTitle: "Sin dolor",
    noPainDesc: "Olvídate de los pinchazos diarios",
    instantResultsTitle: "Resultados inmediatos",
    instantResultsDesc: "Lecturas en tiempo real",
    expertApprovedTitle: "Aprobado por expertos",
    expertApprovedDesc: "Validado clínicamente",
    accurateTitle: "Preciso",
    accurateDesc: "Mediciones confiables",
    yourNewGlucometer: "Tu nuevo glucómetro",
    step: "Paso",
    complete: "completado",
    profileSetupIntro: "Personaliza tu experiencia para mejores resultados",
    home: "Inicio",
    profile: "Perfil",
    learn: "Aprender",
    progress: "Progreso",
    measure: "Medir",
    readyToMeasure: "Listo para medir",
    takeMeasurement: "Tomar medida",
    measuringInProgress: "Midiendo...",
    measurementComplete: "¡Medición completada!",
    yourReading: "Tu lectura",
    mgdl: "mg/dL",
    inRange: "Dentro del rango",
    highAlert: "Alerta alta",
    lowAlert: "Alerta baja",
    trending: "Tendencia",
    trendingUp: "Subiendo",
    trendingDown: "Bajando",
    stable: "Estable",
    lastReading: "Última lectura",
    points: "Puntos",
    streak: "Racha",
    achievements: "Logros",
    howitworks: "Cómo funciona",
    laserTechnology: "Tecnología láser",
    benefits: "Beneficios",
    safety: "Seguridad",
    name: "Nombre",
    age: "Edad",
    diabetesType: "Tipo de diabetes",
    targetRange: "Rango objetivo",
    saveProfile: "Guardar perfil",
    enterName: "Introduce tu nombre",
    type1: "Tipo 1",
    type2: "Tipo 2",
    prediabetes: "Prediabetes",
    gestational: "Gestacional",
    otherDiabetes: "Otro",
    targetRangeDescription: "Rango objetivo de glucosa (mg/dL)",
    howItWorksContent: "Accu-Tech Healthineers utiliza tecnología láser avanzada para medir los niveles de glucosa a través de la piel sin necesidad de pinchazos. El láser penetra en la piel y analiza la concentración de glucosa en la sangre de forma no invasiva.",
    benefitsContent: "- Sin dolor ni molestias\n- Sin consumibles costosos\n- Resultados inmediatos\n- Seguimiento continuo\n- Discreto y conveniente",
    safetyContent: "La tecnología láser de Accu-Tech Healthineers utiliza un láser de baja potencia que es completamente seguro para la piel. El dispositivo ha pasado rigurosas pruebas de seguridad y cumple con todos los estándares médicos internacionales.",
    firstMeasurement: "¡Primera medición!",
    threeDay: "¡Racha de 3 días!",
    sevenDay: "¡Racha de 7 días!",
    profileComplete: "Perfil completo",
    learnExpert: "Experto en aprendizaje",
    readyToStart: "¿Listo para comenzar?",
    tutorialDescription: "Comencemos a explorar todo lo que puedes hacer",
    measureGlucose: "Mide tu glucosa",
    measureGlucoseDescription: "Simula mediciones y prepárate para usar tu dispositivo",
    trackProgress: "Seguimiento de progreso",
    trackProgressDescription: "Visualiza tus lecturas y tendencias a lo largo del tiempo",
    earnAchievements: "Gana logros",
    earnAchievementsDescription: "Completa desafíos y mantén tu motivación",
    setupProfile: "Configura tu perfil",
    profilePrivacyMessage: "Tu información se mantiene privada y segura. La usamos para personalizar tu experiencia.",
    basicInfo: "Información básica",
    healthInfo: "Información de salud",
    lifestyle: "Estilo de vida",
    goals: "Objetivos",
    gender: "Género",
    male: "Masculino",
    female: "Femenino",
    otherGender: "Otro",
    preferNotToSay: "Prefiero no decirlo",
    weight: "Peso",
    exerciseFrequency: "Frecuencia de ejercicio",
    dietType: "Tipo de dieta",
    smoker: "¿Fumas?",
    primaryGoal: "¿Cuál es tu objetivo principal?",
    customGoal: "Objetivo personalizado",
    customGoalPlaceholder: "Describe tu objetivo personal aquí...",
    sedentary: "Sedentario",
    sedentaryDesc: "Poco o nada de ejercicio",
    light: "Ligero",
    lightDesc: "Ejercicio ligero 1-3 días por semana",
    moderate: "Moderado",
    moderateDesc: "Ejercicio moderado 3-5 días por semana",
    active: "Activo",
    activeDesc: "Ejercicio intenso 6-7 días por semana",
    veryActive: "Muy activo",
    veryActiveDesc: "Ejercicio intenso diario o atleta profesional",
    regular: "Regular",
    lowCarb: "Baja en carbohidratos",
    lowFat: "Baja en grasas",
    vegetarian: "Vegetariana",
    vegan: "Vegana",
    betterControl: "Mejor control de glucosa",
    betterControlDesc: "Mantener mis niveles de azúcar más estables",
    loseWeight: "Perder peso",
    loseWeightDesc: "Alcanzar y mantener un peso saludable",
    moreEnergy: "Más energía",
    moreEnergyDesc: "Sentirme con más vitalidad durante el día",
    reduceMedication: "Reducir medicación",
    reduceMedicationDesc: "Reducir mi dependencia de medicamentos",
    custom: "Personalizado",
    customDesc: "Tengo un objetivo específico en mente",
    profileCompletion: "Completado del perfil",
    privacyNote: "Tu información se mantiene privada y segura. Solo la usamos para personalizar tu experiencia.",
    saveAndContinue: "Guardar y continuar",
    language: "Idioma",
    saveAndReturn: "Guardar y volver",
    deviceOnTheWay: "Tu dispositivo está en camino",
    yourDeviceIsBeingShipped: "Tu Accu-Tech Healthineers está siendo enviado a tu dirección",
    ordered: "Ordenado",
    shipping: "Enviando",
    delivered: "Entregado",
    estimatedDelivery: "Entrega estimada",
    days: "días",
    prepareForArrival: "Prepárate para su llegada",
    connectYourDeviceWhenArrives: "Una vez que llegue tu dispositivo, podrás conectarlo para empezar a medir tu glucosa sin dolor",
    learnMore: "Aprender más",
    trackShipment: "Seguir envío",
    connectYourDevice: "Conecta tu dispositivo",
    connectDevice: "Conectar Dispositivo",
    howToConnect: "Cómo conectar tu dispositivo",
    followSteps: "Sigue estos pasos para emparejar tu dispositivo Accu-Tech",
    turnOnDevice: "Enciende tu dispositivo",
    pressButtonForThreeSeconds: "Mantén presionado el botón de encendido durante 3 segundos hasta que veas la luz azul.",
    activatePairingMode: "Activa el modo emparejamiento",
    pressPairingButton: "Presiona el botón de emparejamiento dos veces seguidas. La luz comenzará a parpadear.",
    keepDeviceClose: "Mantén el dispositivo cerca",
    keepDeviceCloseDesc: "Asegúrate de que el dispositivo esté a menos de 10 cm de tu teléfono durante el proceso de emparejamiento.",
    troubleshootingTitle: "¿Tienes problemas para conectar?",
    enoughBattery: "Asegúrate de que tu dispositivo tiene batería suficiente",
    bluetoothActivated: "Verifica que el Bluetooth de tu teléfono esté activado",
    keepDevicesClose: "Mantén el dispositivo y el teléfono cerca durante el emparejamiento",
    restartDevice: "Reinicia el dispositivo si el problema persiste",
    contactSupport: "Si continúas teniendo problemas, contáctanos para asistencia",
    searchingForDevices: "Buscando dispositivos cercanos",
    ensureDeviceReady: "Asegúrate de que tu dispositivo esté encendido y en modo de emparejamiento",
    cancel: "Cancelar",
    connectingToDevice: "Conectando al dispositivo",
    deviceFound: "Se ha encontrado un dispositivo. Estableciendo conexión...",
    connectionFailed: "No se pudo conectar",
    deviceNotDetected: "No se ha detectado el dispositivo Accu-Tech Healthineers. Esto es normal si aún no tienes el dispositivo físico.",
    dontHaveDeviceYet: "¿No tienes tu dispositivo aún?",
    deviceOnTheWayMessage: "Tu dispositivo Accu-Tech Healthineers está en camino. Mientras tanto, puedes explorar la aplicación para familiarizarte con sus funciones.",
    tryAgain: "Intentar de nuevo",
    back: "Volver",
    deviceConnected: "¡Dispositivo conectado!",
    deviceReadyToUse: "Tu dispositivo Accu-Tech Healthineers está listo para usar.",
    startMeasuring: "Comenzar a medir",
    searchDevice: "Buscar dispositivo",
    importantNote: "Nota importante",
    demoVersionNote: "Esta es una versión de demostración. Como aún no tienes el dispositivo físico, la conexión no podrá completarse.",
    bluetoothNotAvailable: "Bluetooth no disponible",
    browserDoesNotSupportBluetooth: "Tu navegador no soporta Bluetooth o está desactivado. Por favor, activa Bluetooth en tu dispositivo.",
    dailyTips: "Consejos Diarios",
    bluetoothUnavailable: "Bluetooth no disponible",
    enableBluetooth: "Activa el Bluetooth en tu dispositivo para conectarte."
  },
  pt: {
    welcome: "Bem-vindo ao Accu-Tech Healthineers",
    welcomeSubtitle: "Seu companheiro para monitoramento de glicose sem dor",
    welcomeToApp: "A nova era do controle do diabetes",
    thankYouMessage: "Obrigado pela sua compra! Estamos preparando seu dispositivo",
    userTestimonial: "Finalmente posso medir minha glicose sem furar os dedos. É incrível!",
    testimonialAuthor: "João M., usuário Accu-Tech Healthineers",
    deviceArrivalMessage: "Enquanto você espera a chegada do seu Accu-Tech Healthineers, vamos explorar o aplicativo",
    selectLanguage: "Selecionar idioma",
    spanish: "Espanhol",
    portuguese: "Português",
    continue: "Continuar",
    skip: "Pular",
    next: "Próximo",
    back: "Voltar",
    getStarted: "Começar",
    howItWorks: "Como funciona?",
    laserTechnologyIntro: "Nossa revolucionária tecnologia a laser mede sua glicose sem dor",
    laserEmissionTitle: "Emissão do laser",
    laserEmissionDesc: "Um laser infravermelho seguro penetra levemente na pele",
    bloodlessAnalysisTitle: "Análise sem sangue",
    bloodlessAnalysisDesc: "A luz refletida analisa as moléculas de glicose",
    instantReadingTitle: "Leitura instantânea",
    instantReadingDesc: "O dispositivo calcula seu nível de glicose em segundos",
    scientificallyProven: "Tecnologia respaldada por pesquisas científicas avançadas",
    keyBenefits: "Principais benefícios",
    benefitsIntro: "Descubra por que o Accu-Tech Healthineers vai transformar sua vida",
    noPainTitle: "Sem dor",
    noPainDesc: "Esqueça as picadas diárias",
    instantResultsTitle: "Resultados imediatos",
    instantResultsDesc: "Leituras em tempo real",
    expertApprovedTitle: "Aprovado por especialistas",
    expertApprovedDesc: "Validado clinicamente",
    accurateTitle: "Preciso",
    accurateDesc: "Medições confiáveis",
    yourNewGlucometer: "Seu novo glicosímetro",
    step: "Passo",
    complete: "concluído",
    profileSetupIntro: "Personalize sua experiência para melhores resultados",
    home: "Início",
    profile: "Perfil",
    learn: "Aprender",
    progress: "Progresso",
    measure: "Medir",
    readyToMeasure: "Pronto para medir",
    takeMeasurement: "Fazer medição",
    measuringInProgress: "Medindo...",
    measurementComplete: "Medição completa!",
    yourReading: "Sua leitura",
    mgdl: "mg/dL",
    inRange: "Dentro da faixa",
    highAlert: "Alerta alto",
    lowAlert: "Alerta baixo",
    trending: "Tendência",
    trendingUp: "Subindo",
    trendingDown: "Descendo",
    stable: "Estável",
    lastReading: "Última leitura",
    points: "Pontos",
    streak: "Sequência",
    achievements: "Conquistas",
    howitworks: "Como funciona",
    laserTechnology: "Tecnologia laser",
    benefits: "Benefícios",
    safety: "Segurança",
    name: "Nome",
    age: "Idade",
    diabetesType: "Tipo de diabetes",
    targetRange: "Faixa alvo",
    saveProfile: "Salvar perfil",
    enterName: "Digite seu nome",
    type1: "Tipo 1",
    type2: "Tipo 2",
    prediabetes: "Pré-diabetes",
    gestational: "Gestacional",
    otherDiabetes: "Outro",
    targetRangeDescription: "Faixa alvo de glicose (mg/dL)",
    howItWorksContent: "O Accu-Tech Healthineers usa tecnologia laser avançada para medir os níveis de glicose através da pele sem a necessidade de picadas. O laser penetra na pele e analisa a concentração de glicose no sangue de forma não invasiva.",
    benefitsContent: "- Sem dor ou desconforto\n- Sem consumíveis caros\n- Resultados imediatos\n- Monitoramento contínuo\n- Discreto e conveniente",
    safetyContent: "A tecnologia laser Accu-Tech Healthineers usa um laser de baixa potência que é completamente seguro para a pele. O dispositivo passou por testes rigorosos de segurança e atende a todos os padrões médicos internacionais.",
    firstMeasurement: "Primeira medição!",
    threeDay: "Sequência de 3 dias!",
    sevenDay: "Sequência de 7 dias!",
    profileComplete: "Perfil completo",
    learnExpert: "Especialista em aprendizado",
    readyToStart: "Pronto para começar?",
    tutorialDescription: "Vamos começar a explorar tudo o que você pode fazer",
    measureGlucose: "Meça sua glicose",
    measureGlucoseDescription: "Simule medições e prepare-se para usar seu dispositivo",
    trackProgress: "Acompanhe seu progresso",
    trackProgressDescription: "Visualize suas leituras e tendências ao longo do tempo",
    earnAchievements: "Ganhe conquistas",
    earnAchievementsDescription: "Complete desafios e mantenha sua motivação",
    setupProfile: "Configure seu perfil",
    profilePrivacyMessage: "Suas informações são mantidas privadas e seguras. Utilizamos para personalizar sua experiência.",
    basicInfo: "Informações básicas",
    healthInfo: "Informações de saúde",
    lifestyle: "Estilo de vida",
    goals: "Objetivos",
    gender: "Gênero",
    male: "Masculino",
    female: "Feminino",
    otherGender: "Outro",
    preferNotToSay: "Prefiro não dizer",
    weight: "Peso",
    exerciseFrequency: "Frequência de exercícios",
    dietType: "Tipo de dieta",
    smoker: "Você fuma?",
    primaryGoal: "Qual é seu objetivo principal?",
    customGoal: "Objetivo personalizado",
    customGoalPlaceholder: "Descreva seu objetivo pessoal aqui...",
    sedentary: "Sedentário",
    sedentaryDesc: "Pouco ou nenhum exercício",
    light: "Leve",
    lightDesc: "Exercício leve 1-3 dias por semana",
    moderate: "Moderado",
    moderateDesc: "Exercício moderado 3-5 dias por semana",
    active: "Ativo",
    activeDesc: "Exercício intenso 6-7 dias por semana",
    veryActive: "Muito ativo",
    veryActiveDesc: "Exercício intenso diário ou atleta profissional",
    regular: "Regular",
    lowCarb: "Baixo carboidrato",
    lowFat: "Baixa gordura",
    vegetarian: "Vegetariana",
    vegan: "Vegana",
    betterControl: "Melhor controle de glicose",
    betterControlDesc: "Manter meus níveis de açúcar mais estáveis",
    loseWeight: "Perder peso",
    loseWeightDesc: "Alcançar e manter um peso saudável",
    moreEnergy: "Mais energia",
    moreEnergyDesc: "Me sentir com mais vitalidade durante o dia",
    reduceMedication: "Reduzir medicação",
    reduceMedicationDesc: "Reduzir minha dependência de medicamentos",
    custom: "Personalizado",
    customDesc: "Tenho um objetivo específico em mente",
    profileCompletion: "Conclusão do perfil",
    privacyNote: "Suas informações são mantidas privadas e seguras. Usamos apenas para personalizar sua experiência.",
    saveAndContinue: "Salvar e continuar",
    language: "Idioma",
    saveAndReturn: "Salvar e voltar",
    deviceOnTheWay: "Seu dispositivo está a caminho",
    yourDeviceIsBeingShipped: "Seu Accu-Tech Healthineers está sendo enviado para o seu endereço",
    ordered: "Pedido",
    shipping: "Enviando",
    delivered: "Entregue",
    estimatedDelivery: "Entrega estimada",
    days: "dias",
    prepareForArrival: "Prepare-se para a chegada",
    connectYourDeviceWhenArrives: "Quando seu dispositivo chegar, você poderá conectá-lo para começar a medir sua glicose sem dor",
    learnMore: "Saiba mais",
    trackShipment: "Rastrear envio",
    connectYourDevice: "Conecte seu dispositivo",
    connectDevice: "Conectar Dispositivo",
    howToConnect: "Como conectar seu dispositivo",
    followSteps: "Siga estas etapas para emparelhar seu dispositivo Accu-Tech",
    turnOnDevice: "Ligue seu dispositivo",
    pressButtonForThreeSeconds: "Mantenha pressionado o botão de energia por 3 segundos até ver a luz azul.",
    activatePairingMode: "Ative o modo de emparelhamento",
    pressPairingButton: "Pressione o botão de emparelhamento duas vezes seguidas. A luz começará a piscar.",
    keepDeviceClose: "Mantenha o dispositivo próximo",
    keepDeviceCloseDesc: "Certifique-se de que o dispositivo esteja a menos de 10 cm do seu telefone durante o processo de emparelhamento.",
    troubleshootingTitle: "Problemas para conectar?",
    enoughBattery: "Certifique-se de que seu dispositivo tenha bateria suficiente",
    bluetoothActivated: "Verifique se o Bluetooth do seu telefone está ativado",
    keepDevicesClose: "Mantenha o dispositivo e o telefone próximos durante o emparelhamento",
    restartDevice: "Reinicie o dispositivo se o problema persistir",
    contactSupport: "Se continuar tendo problemas, entre em contato conosco para obter assistência",
    searchingForDevices: "Procurando dispositivos próximos",
    ensureDeviceReady: "Certifique-se de que seu dispositivo esteja ligado e no modo de emparelhamento",
    cancel: "Cancelar",
    connectingToDevice: "Conectando ao dispositivo",
    deviceFound: "Um dispositivo foi encontrado. Estabelecendo conexão...",
    connectionFailed: "Não foi possível conectar",
    deviceNotDetected: "O dispositivo Accu-Tech Healthineers não foi detectado. Isso é normal se você ainda não tiver o dispositivo físico.",
    dontHaveDeviceYet: "Ainda não tem seu dispositivo?",
    deviceOnTheWayMessage: "Seu dispositivo Accu-Tech Healthineers está a caminho. Enquanto isso, você pode explorar o aplicativo para se familiarizar com seus recursos.",
    tryAgain: "Tentar novamente",
    back: "Voltar",
    deviceConnected: "Dispositivo conectado!",
    deviceReadyToUse: "Seu dispositivo Accu-Tech Healthineers está pronto para uso.",
    startMeasuring: "Começar a medir",
    searchDevice: "Procurar dispositivo",
    importantNote: "Nota importante",
    demoVersionNote: "Esta é uma versão de demonstração. Como você ainda não tem o dispositivo físico, a conexão não poderá ser concluída.",
    bluetoothNotAvailable: "Bluetooth não disponível",
    browserDoesNotSupportBluetooth: "Seu navegador não suporta Bluetooth ou está desativado. Ative o Bluetooth no seu dispositivo.",
    dailyTips: "Dicas Diárias",
    bluetoothUnavailable: "Bluetooth indisponível",
    enableBluetooth: "Ative o Bluetooth no seu dispositivo para se conectar."
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('es');

  useEffect(() => {
    // Try to get saved language preference from local storage
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && (savedLanguage === 'es' || savedLanguage === 'pt')) {
      setLanguageState(savedLanguage);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const translate = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, translate }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
