// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zccjmsppyzvvguxkjnuv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpjY2ptc3BweXp2dmd1eGtqbnV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwMzUyMDQsImV4cCI6MjA1ODYxMTIwNH0.QrIgKMny77J-nkpZWow2gGPXAtXuIbyjfVrDeMpTsAE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);